services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmqrevision
    ports:
      - '5672:5672' # AMQP Port
      - '15672:15672' # Management interface port
    environment:
      - RABBITMQ_DEFAULT_USER= guest
      - RABBITMQ_DEFAULT_PASS= guest
